exclude: "migrations|.git|.github"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: ["--skip-string-normalization"]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: |
          env DATABASE_URL="postgres://a:a@127.0.0.1:5432/a" CELERY_BROKER_URL="" USE_DOCKER=""
          python -m pylint
        language: system
        types: [python]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]
        additional_dependencies:
          - flake8-isort==6.0.0
          - flake8-bugbear==22.12.6
          - flake8-no-pep420==2.3.0
          - flake8-print==5.0.0

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.292
    hooks:
      - id: pyright
        entry: python -m pyright

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
