version: "3"

volumes:
  todo_local_postgres_data: {}
  todo_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: todo_local_django
    container_name: todo_local_django
    depends_on:
      - postgres
      - rabbitmq
      - mailhog
    volumes:
      - ./app:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: todo_local_postgres
    container_name: todo_local_postgres
    volumes:
      - todo_local_postgres_data:/var/lib/postgresql/data
      - todo_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: todo_local_docs
    container_name: todo_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./app:/app:z
    ports:
      - "9000:9000"
    command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: todo_local_mailhog
    ports:
      - "8025:8025"

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: todo_local_rabbitmq
    ports:
      - "5172:5672"
      - "15172:15672"

  celeryworker:
    <<: *django
    image: todo_local_celeryworker
    container_name: todo_local_celeryworker
    depends_on:
      - rabbitmq
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: todo_local_celerybeat
    container_name: todo_local_celerybeat
    depends_on:
      - rabbitmq
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: todo_local_flower
    container_name: todo_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
